version: "3.9"

services:
  redis-service:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
      
  views-service:
    image: views-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: views-service
    ports:
      - "8888:8888"
    volumes:
      - /path/to/credential.json:/credential.json
    environment:
      - PORT=8888
      - LOG_LEVEL=info
      - CORS=*
      - REDIS=redis://redis-service:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/credential.json
      - ID=xxxxxxxxxxxxx
      - DOMAIN=ambersun1234.github.io
      - START_DATE=2022-08-31
    networks:
      - mynetwork

networks:
  mynetwork:
