{{- if .Values.views.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: views-credential
stringData:
  redis: "redis://redis-master.default.svc.cluster.local"
  id: "{{ .Values.views.settings.id }}"
  credential.json: |
    {
      "your_credentials": "your_credentials"
    }
{{- end }}
